routes/web.php
<?php
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'DashboardController@index')->name('home');
    Route::resource('presenters', 'PresenterController');
    Route::resource('talks', 'TalkController');
});

Route::group(['middleware' => ['guest']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('presenters', 'PresenterController')->only(['index', 'show']);
    Route::resource('talks', 'TalkController')->only(['index', 'show']);
});

Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);
Broadcast::routes();

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <div class="flex flex-col md:flex-row">

        <div class="w-full md:w-1/2 xl:w-1/3">
            <h2 class="text-2xl">Presenters:</h2>
            <a href="{{ route('presenters.create') }}">New Presenter...</a>
            <br>
            <ul>
                @forelse($presenters as $presenter)
                    <li>
                        <a href="{{ route('presenters.edit', [$presenter]) }}">
                            {{ $presenter->name }}
                        </a> with {{ $presenter->talks->count() }} {{ \Illuminate\Support\Str::plural('talk', $presenter->talks->count()) }}
                    </li>
                @empty
                    <li><em>No presenters...</em></li>
                @endforelse
            </ul>
        </div>
        <div class="w-full md:w-1/2 xl:w-1/3">
            <h2 class="text-2xl">Talks:</h2>
            <a href="{{ route('talks.create') }}">New Talk...</a>
            <br>
            <ul>
                @forelse($talks as $talk)
                    <li>
                        <a href="{{ route('talks.edit', [$talk]) }}">
                            {{ $talk->title }}
                        </a> by {{ $talk->presenter->name }}
                    </li>
                @empty
                    <li><em>No talks...</em></li>
                @endforelse
            </ul>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection