routes/web.php
<?php
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'DashboardController@index')->name('home');
    Route::resource('presenters', 'PresenterController');
    Route::resource('talks', 'TalkController');
});

Route::group(['middleware' => ['guest']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('presenters', 'PresenterController')->only(['index', 'show']);
    Route::resource('talks', 'TalkController')->only(['index', 'show']);
});

Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);
Broadcast::routes();

app/Talk.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Talk extends Model
{
    protected $fillable = ['title', 'starts_at', 'ends_at', 'slides_url', 'presenter_id'];

    protected $dates = ['starts_at', 'ends_at'];

    public function presenter()
    {
        return $this->belongsTo(Presenter::class)->withDefault([
            'name' => 'A Surprise, Guest Speaker',
        ]);
    }

    public function getSluggedTitleAttribute()
    {
        return Str::slug($this->title);
    }

    public function scopeCurrent($query)
    {
        $now = Carbon::now();
        return $query->where('starts_at', '<=', $now)
            ->where('ends_at', '>', $now);
    }

    public function scopePrevious($query)
    {
        return $query->where('ends_at', '<', Carbon::now())->orderBy('starts_at');
    }

    public function scopeUpcoming($query)
    {
        return $query->where('starts_at', '>', Carbon::now())->orderBy('starts_at');
    }

    public function isCurrent()
    {
        $now = Carbon::now();
        return $this->starts_at <= $now && $this->ends_at > $now;
    }

    public function isPrevious()
    {
        $now = Carbon::now();
        return $this->ends_at < $now;
    }

    public function isUpcoming()
    {
        $now = Carbon::now();
        return $this->starts_at > $now;
    }
}

app/Http/Controllers/TalkController.php
<?php

namespace App\Http\Controllers;

use App\Events\TalkUpdated;
use App\Http\Requests\CreateTalkRequest;
use App\Presenter;
use App\Talk;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TalkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $talks = Talk::with('presenter')->orderBy('starts_at')->get();
        return view((Auth::check() ? '' : 'guest.') . 'talks.index', compact('talks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $presenters = Presenter::orderBy('name')->get();
        return view('talks.create', compact('presenters'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTalkRequest $request)
    {
        $talk = Talk::create([
            'title' => $request->get('title'),
            'presenter_id' => $request->get('presenter_id') ?: null,
            'starts_at' => (new Carbon($request->get('starts_at'), 'America/New_York'))
                ->setTimezone('UTC'),
            'ends_at' => (new Carbon($request->get('ends_at'), 'America/New_York'))
                ->setTimezone('UTC'),
            'slides_url' => $request->get('slides_url') ?: null,
        ]);
        return redirect()->route('talks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Talk  $talk
     * @return \Illuminate\Http\Response
     */
    public function show(Talk $talk)
    {
        $talk->load('presenter');
        return view((Auth::check() ? '' : 'guest.') . 'talks.show', compact('talk'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Talk  $talk
     * @return \Illuminate\Http\Response
     */
    public function edit(Talk $talk)
    {
        $presenters = Presenter::orderBy('name')->get();
        return view('talks.edit', compact('talk', 'presenters'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Talk                $talk
     *
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function update(Request $request, Talk $talk)
    {
        $talk->load('presenter');
        if ($request->has('title')) {
            $talk->title = $request->get('title');
        }

        if ($request->has('starts_at')) {
            $talk->starts_at = (new Carbon($request->get('starts_at'), 'America/New_York'))
                ->setTimezone('UTC');
        }

        if ($request->has('ends_at')) {
            $talk->ends_at = (new Carbon($request->get('ends_at'), 'America/New_York'))
                ->setTimezone('UTC');
        }

        if ($request->has('slides_url')) {
            $talk->slides_url = $request->get('slides_url') ?: null;
        }

        if ($request->has('contents')) {
            $talk->contents = $request->get('contents') ?: '';
        }

        if ($request->has('presenter')) {
            $presenter = Presenter::find($request->get('presenter'));
            $talk->presenter()->associate($presenter);
        }

        $talk->save();
        broadcast(new TalkUpdated($talk));
        return response('', 204);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Talk  $talk
     * @return \Illuminate\Http\Response
     */
    public function destroy(Talk $talk)
    {
        //
    }
}

resources/views/talks/create.blade.php
@extends('layouts.app')

@section('content')
    <form method="post" action="{{ route('talks.store') }}">
        @csrf
        <header class="flex flex-col md:flex-row items-center justify-between mb-8">
            <div class="inline-block relative text-3xl w-1/2">
                <input type="text" id="title" name="title"
                       class="bg-white w-full text-3xl bg-white border border-light-shades hover:border-light-accent shadow"
                       placeholder="">
            </div>
            <div class="inline-block relative w-64">
                <select id="presenter" name="presenter_id"
                        class="block appearance-none text-xl uppercase tracking-wider w-full bg-white border border-light-shades hover:border-light-accent px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline">
                    <option value="">Select A Presenter</option>
                    <option disabled>---</option>
                    @foreach ($presenters as $presenter)
                        <option value="{{ $presenter->id }}">
                            {{ $presenter->name }}
                        </option>
                    @endforeach
                </select>
                <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-light-accent">
                    <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/>
                    </svg>
                </div>
            </div>
        </header>
        <section class="mb-8">

            <label for="starts_at" class="mr-8">Start/End: </label>
            <input type="datetime-local" id="starts_at" name="starts_at" value="{{ Carbon\Carbon::now()->addHour()->setMinutes(0)->setSeconds(0)->setTimezone('America/New_York')->toDateTimeLocalString() }}" />
            <input type="datetime-local" id="ends_at" name="ends_at" value="{{ Carbon\Carbon::now()->addHour()->setMinutes(30)->setSeconds(0)->setTimezone('America/New_York')->toDateTimeLocalString() }}" />
        </section>
        <section class="flex flex-col md:flex-row items-center justify-between mb-8">
            <label for="slides_url" class="mr-8">Slides: </label>
            <input type="url" id="slides_url" name="slides_url"
                   class="bg-white flex-1 bg-white border border-light-shades hover:border-light-accent shadow"
                   value="">
        </section>
        <section class="mb-8">
            <button type="submit" class="shadow bg-dark-accent text-light-shades focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" type="button">
                {{ __('Save') }}
            </button>
        </section>
    </form>
@endsection

resources/views/talks/edit.blade.php
@extends('layouts.app')

@section('content')
    <form action="#">
        <header class="flex flex-col md:flex-row items-center justify-between mb-8">
            <div class="inline-block relative text-3xl w-1/2">
                <input type="text" id="title"
                       class="bg-white w-full text-3xl bg-white border border-light-shades hover:border-light-accent shadow"
                       value="{{ $talk->title }}">
            </div>
            <div class="inline-block relative w-64">
                <select id="presenter"
                        class="block appearance-none text-xl uppercase tracking-wider w-full bg-white border border-light-shades hover:border-light-accent px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline">
                    <option>Select A Presenter</option>
                    <option disabled>---</option>
                    @foreach ($presenters as $presenter)
                        <option value="{{ $presenter->id }}" {{ $presenter->id === $talk->presenter->id ? 'selected ' : '' }}>
                            {{ $presenter->name }}
                        </option>
                    @endforeach
                </select>
                <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-light-accent">
                    <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/>
                    </svg>
                </div>
            </div>
        </header>
        <section>
            <input type="datetime-local" id="starts_at" value="{{ $talk->starts_at->setTimezone('America/New_York')->toDateTimeLocalString() }}" />
            <input type="datetime-local" id="ends_at" value="{{ $talk->ends_at->setTimezone('America/New_York')->toDateTimeLocalString() }}" />
        </section>
        <section>
            <input type="url" id="slides_url"
                   class="bg-white w-full bg-white border border-light-shades hover:border-light-accent shadow"
                   value="{{ $talk->slides_url }}">
        </section>
        <main class="">
            <textarea class="w-full shadow rounded font-mono" name="contents" id="contents" cols="30"
                      rows="10">{{ $talk->contents }}</textarea>
        </main>
    </form>
@endsection

@push('scripts')
    <script>
        var counter = 0;
        {{--window.Echo.join('talk.{{ $talk->id }}')--}}
        {{--    .here((users) => {--}}
        {{--        counter = users.length;--}}
        {{--        updateCounter();--}}
        {{--    })--}}
        {{--    .joining((user) => {--}}
        {{--        counter++;--}}
        {{--        updateCounter();--}}
        {{--    })--}}
        {{--    .leaving((user) => {--}}
        {{--        counter--;--}}
        {{--        updateCounter();--}}
        {{--    });--}}

        function updateCounter() {
            document.getElementById('counter').innerText = counter;
        }

        function titleChanged() {
            console.log("title changed");
            window.axios.patch('/talks/{{ $talk->id }}', {
                title: document.getElementById('title').value
            }).then((response) => {
            });
        }
        function presenterChanged() {
            console.log("presenter changed");
            window.axios.patch('/talks/{{ $talk->id }}', {
                presenter: document.getElementById('presenter').value
            }).then((response) => {
            });
        }
        function startsAtChanged() {
            console.log("startsAt changed");
            window.axios.patch('/talks/{{ $talk->id }}', {
                starts_at: document.getElementById('starts_at').value
            }).then((response) => {
            });
        }
        function endsAtChanged() {
            console.log("endsAt changed");
            window.axios.patch('/talks/{{ $talk->id }}', {
                ends_at: document.getElementById('ends_at').value
            }).then((response) => {
            });
        }
        function slidesChanged() {
            window.axios.patch('/talks/{{ $talk->id }}', {
                slides_url: document.getElementById('slides_url').value
            }).then((response) => {
            });
        }
        var contentsChanged = debounce(function () {
            window.axios.patch('/talks/{{ $talk->id }}', {
                contents: document.getElementById('contents').value
            }).then((response) => {
            });
        }, 750, false);

        function debounce(func, wait, immediate) {
            var timeout;

            return function executedFunction() {
                var context = this;
                var args = arguments;

                var later = function() {
                    timeout = null;
                    if (!immediate) func.apply(context, args);
                };

                var callNow = immediate && !timeout;

                clearTimeout(timeout);

                timeout = setTimeout(later, wait);

                if (callNow) func.apply(context, args);
            }
        }

        document.getElementById('title').onblur = titleChanged;
        document.getElementById('presenter').onchange = presenterChanged;
        document.getElementById('starts_at').onchange = startsAtChanged;
        document.getElementById('ends_at').onchange = endsAtChanged;
        document.getElementById('slides_url').onchange = slidesChanged;
        document.getElementById('contents').onkeyup = contentsChanged;
    </script>
@endpush

resources/views/talks/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-md mx-auto max-w-2xl w-full bg-light-shades">
        @foreach ($talks as $talk)
            <div class="bg-white rounded mb-8 shadow-md">
                <div class="flex items-center">
                    <div class="text-left p-4 bg-white w-24">
                        <img class="rounded-full shadow-lg"
                             src="https://avatars.io/twitter/{{ $talk->presenter->twitter }}/small" alt="{{ $talk->presenter->twitter }}"/>
                    </div>
                    <div class="text-left p-4 bg-white w-32">
                        {{ $talk->presenter->name }}
                    </div>
                    <div class="text-left p-4 bg-white">
                        <a class="text-main-brand font-bold" href="{{ route('talks.edit', [$talk]) }}">
                            {{ $talk->title }}
                        </a>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection